version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "my_postgres"
    ports:
      # Set to 54320 to prevent conflict with potentially locally running postgres
      - "54320:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
volumes:
  my_dbdata: